name: kc-wildfire-terrain-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - numpy
  - shapely
  - requests
  - pyarrow
  - rasterio
  - rioxarray
  - xarray
  - xarray-spatial
  - rio-cogeo
  - pystac
  - pip
